# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cal_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


#pyuic5 -x cal_1.ui -o calc.py


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(200, 360)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(200, 360))
        MainWindow.setMaximumSize(QtCore.QSize(200, 360))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_rez = QtWidgets.QLabel(self.centralwidget)
        self.label_rez.setGeometry(QtCore.QRect(0, 0, 200, 60))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_rez.setFont(font)
        self.label_rez.setAutoFillBackground(False)
        self.label_rez.setStyleSheet("background-color: rgb(0, 170, 127);\n"
"color: rgb(255, 255, 0);")
        self.label_rez.setObjectName("label_rez")
        self.pushButton_plusminus = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_plusminus.setGeometry(QtCore.QRect(0, 310, 50, 50))
        self.pushButton_plusminus.setObjectName("pushButton_plusminus")
        self.pushButton_2_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2_4.setGeometry(QtCore.QRect(0, 210, 50, 50))
        self.pushButton_2_4.setObjectName("pushButton_2_4")
        self.pushButton_3_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3_1.setGeometry(QtCore.QRect(0, 260, 50, 50))
        self.pushButton_3_1.setObjectName("pushButton_3_1")
        self.pushButton_4_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4_7.setGeometry(QtCore.QRect(0, 160, 50, 50))
        self.pushButton_4_7.setObjectName("pushButton_4_7")
        self.pushButton_5_persent = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5_persent.setGeometry(QtCore.QRect(0, 110, 50, 50))
        self.pushButton_5_persent.setObjectName("pushButton_5_persent")
        self.pushButton_6_close = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6_close.setGeometry(QtCore.QRect(0, 60, 50, 50))
        self.pushButton_6_close.setObjectName("pushButton_6_close")
        self.pushButton_7_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7_8.setGeometry(QtCore.QRect(50, 160, 50, 50))
        self.pushButton_7_8.setObjectName("pushButton_7_8")
        self.pushButton_8_skobkaleft = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8_skobkaleft.setGeometry(QtCore.QRect(50, 110, 50, 50))
        self.pushButton_8_skobkaleft.setObjectName("pushButton_8_skobkaleft")
        self.pushButton_9_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9_2.setGeometry(QtCore.QRect(50, 260, 50, 50))
        self.pushButton_9_2.setObjectName("pushButton_9_2")
        self.pushButton_10_0 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10_0.setGeometry(QtCore.QRect(50, 310, 50, 50))
        self.pushButton_10_0.setObjectName("pushButton_10_0")
        self.pushButton_11_del = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11_del.setGeometry(QtCore.QRect(50, 60, 50, 50))
        self.pushButton_11_del.setObjectName("pushButton_11_del")
        self.pushButton_12_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_12_5.setGeometry(QtCore.QRect(50, 210, 50, 50))
        self.pushButton_12_5.setObjectName("pushButton_12_5")
        self.pushButton_13_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_13_9.setGeometry(QtCore.QRect(100, 160, 50, 50))
        self.pushButton_13_9.setObjectName("pushButton_13_9")
        self.pushButton_14_skobkarait = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_14_skobkarait.setGeometry(QtCore.QRect(100, 110, 50, 50))
        self.pushButton_14_skobkarait.setObjectName("pushButton_14_skobkarait")
        self.pushButton_15_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_15_3.setGeometry(QtCore.QRect(100, 260, 50, 50))
        self.pushButton_15_3.setObjectName("pushButton_15_3")
        self.pushButton_16_tochka = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_16_tochka.setGeometry(QtCore.QRect(100, 310, 50, 50))
        self.pushButton_16_tochka.setObjectName("pushButton_16_tochka")
        self.pushButton_17_clear = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_17_clear.setGeometry(QtCore.QRect(100, 60, 50, 50))
        self.pushButton_17_clear.setObjectName("pushButton_17_clear")
        self.pushButton_18_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_18_6.setGeometry(QtCore.QRect(100, 210, 50, 50))
        self.pushButton_18_6.setObjectName("pushButton_18_6")
        self.pushButton_19_mines = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_19_mines.setGeometry(QtCore.QRect(150, 160, 50, 50))
        self.pushButton_19_mines.setObjectName("pushButton_19_mines")
        self.pushButton_20_mnogenie = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_20_mnogenie.setGeometry(QtCore.QRect(150, 110, 50, 50))
        self.pushButton_20_mnogenie.setObjectName("pushButton_20_mnogenie")
        self.pushButton_21_ravno = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_21_ravno.setGeometry(QtCore.QRect(150, 260, 50, 100))
        self.pushButton_21_ravno.setObjectName("pushButton_21_ravno")
        self.pushButton_23_naklcherta = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_23_naklcherta.setGeometry(QtCore.QRect(150, 60, 50, 50))
        self.pushButton_23_naklcherta.setObjectName("pushButton_23_naklcherta")
        self.pushButton_24_plase = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_24_plase.setGeometry(QtCore.QRect(150, 210, 50, 50))
        self.pushButton_24_plase.setObjectName("pushButton_24_plase")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.add_function()

        self.is_eqval = False

        


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Cal", "ff"))
        self.label_rez.setText(_translate("MainWindow", "0"))

        self.pushButton_plusminus.setText(_translate("MainWindow", "+-"))
        self.pushButton_2_4.setText(_translate("MainWindow", "4"))
        self.pushButton_3_1.setText(_translate("MainWindow", "1"))
        self.pushButton_4_7.setText(_translate("MainWindow", "7"))
        #self.pushButton_5_persent.setText(_translate("MainWindow", "%"))
        self.pushButton_6_close.setText(_translate("MainWindow", "close"))
        self.pushButton_7_8.setText(_translate("MainWindow", "8"))
        self.pushButton_8_skobkaleft.setText(_translate("MainWindow", "("))
        self.pushButton_9_2.setText(_translate("MainWindow", "2"))
        self.pushButton_10_0.setText(_translate("MainWindow", "0"))
        self.pushButton_11_del.setText(_translate("MainWindow", "delete"))
        self.pushButton_12_5.setText(_translate("MainWindow", "5"))
        self.pushButton_13_9.setText(_translate("MainWindow", "9"))
        self.pushButton_14_skobkarait.setText(_translate("MainWindow", ")"))
        self.pushButton_15_3.setText(_translate("MainWindow", "3"))
        self.pushButton_16_tochka.setText(_translate("MainWindow", "."))
        self.pushButton_17_clear.setText(_translate("MainWindow", "clear"))
        self.pushButton_18_6.setText(_translate("MainWindow", "6"))
        self.pushButton_19_mines.setText(_translate("MainWindow", "-"))
        self.pushButton_20_mnogenie.setText(_translate("MainWindow", "*"))
        self.pushButton_21_ravno.setText(_translate("MainWindow", "="))
        self.pushButton_23_naklcherta.setText(_translate("MainWindow", "/"))
        self.pushButton_24_plase.setText(_translate("MainWindow", "+"))

    def add_function(self):

        self.pushButton_plusminus.clicked.connect(lambda: self.write_number(self.pushButton_19_mines.text()))
        self.pushButton_2_4.clicked.connect(lambda: self.write_number(self.pushButton_2_4.text()))
        self.pushButton_3_1.clicked.connect(lambda: self.write_number(self.pushButton_3_1.text()))
        self.pushButton_4_7.clicked.connect(lambda: self.write_number(self.pushButton_4_7.text()))
        self.pushButton_5_persent.clicked.connect(lambda: self.write_number(self.pushButton_5_persent.text()))
        self.pushButton_7_8.clicked.connect(lambda: self.write_number(self.pushButton_7_8.text()))
        self.pushButton_8_skobkaleft.clicked.connect(lambda: self.write_number(self.pushButton_8_skobkaleft.text()))
        self.pushButton_9_2.clicked.connect(lambda: self.write_number(self.pushButton_9_2.text()))
        self.pushButton_10_0.clicked.connect(lambda: self.write_number(self.pushButton_10_0.text()))
        
        self.pushButton_12_5.clicked.connect(lambda: self.write_number(self.pushButton_12_5.text()))
        self.pushButton_13_9.clicked.connect(lambda: self.write_number(self.pushButton_13_9.text()))
        self.pushButton_14_skobkarait.clicked.connect(lambda: self.write_number(self.pushButton_14_skobkarait.text()))
        self.pushButton_15_3.clicked.connect(lambda: self.write_number(self.pushButton_15_3.text()))
        self.pushButton_16_tochka.clicked.connect(lambda: self.write_number(self.pushButton_16_tochka.text()))
        self.pushButton_17_clear.clicked.connect(lambda: self.write_number(self.pushButton_17_clear.text()))
        self.pushButton_18_6.clicked.connect(lambda: self.write_number(self.pushButton_18_6.text()))
        self.pushButton_19_mines.clicked.connect(lambda: self.write_number(self.pushButton_19_mines.text()))
        self.pushButton_20_mnogenie.clicked.connect(lambda: self.write_number(self.pushButton_20_mnogenie.text()))
      
        self.pushButton_23_naklcherta.clicked.connect(lambda: self.write_number(self.pushButton_23_naklcherta.text()))
        self.pushButton_24_plase.clicked.connect(lambda: self.write_number(self.pushButton_24_plase.text()))



        self.pushButton_6_close.clicked.connect(self.exit_)
        self.pushButton_21_ravno.clicked.connect(self.rez)
        self.pushButton_11_del.clicked.connect(self.del_1)



    def rez(self):
        if not self.is_eqval:
            res = eval(self.label_rez.text())
            #self.label_rez.setText("Рез: " + str(res))
            self.label_rez.setText(str(res))
            self.is_eqval = True
        else:
            error = QMessageBox()
            error.setWindowTitle("Ошибка")
            error.setText("Сейчас это действие выполнить нельзя")
            error.setIcon(QMessageBox.Warning)
            error.setStandardButtons(QMessageBox.Ok |QMessageBox.Reset| QMessageBox.Cancel)
            
            error.setDefaultButton(QMessageBox.Ok)
            error.setInformativeText("Два раза действие не выполнять")
            error.setDetailedText("Детали")

            error.buttonClicked.connect(self.popup_action)

            error.exec_()

    def del_1(self):
        self.label_rez.setText("")




    def exit_(self):
        exit()

    def write_number(self, number):
        print(number)

        if self.label_rez.text() == "0" or self.is_eqval:
            self.label_rez.setText(number)
            self.is_eqval = False
        else:
            self.label_rez.setText(self.label_rez.text() + number)

    def popup_action(self,btn):
        if btn.text() == "Ok":
            print("print ok")
        elif btn.text() == "Reset":
            self.label_rez.setText("")
            self.is_eqval = False

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
