# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QmessageBox.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)

        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")

        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(125, 180, 100, 25))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.clicked.connect(self.exit1)
        self.pushButton_4.setText("Exit")


        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))


    def exit1(self):
        msgBox = QMessageBox()
        msgBox.setIcon(QMessageBox.Information)
        msgBox.setText( "Всплывающее окно окна сообщения" )
        msgBox.setWindowTitle( "Пример QMessageBox" )
        msgBox.setStandardButtons(QMessageBox.Ok | QMessageBox.Cancel )
        #msgBox.buttonClicked.connect(msgButtonClick)

        returnValue = msgBox.exec_() 
        if returnValue == QMessageBox.Ok:
            while True:
                msgBox = QMessageBox()
                msgBox.setIcon(QMessageBox.Information)
                msgBox.setText( "Error 0E12030511AC" )
                msgBox.setWindowTitle( "Error" )
                msgBox.setStandardButtons(QMessageBox.Ok | QMessageBox.Cancel )
                returnValue = msgBox.exec_() 
                if returnValue == QMessageBox.Cancel:
                    exit()
                    
        else:
            msgBox = QMessageBox()
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setText( "Cancel" )
            msgBox.setWindowTitle( "Пример QMessageBox" )
            msgBox.setStandardButtons(QMessageBox.Ok  )
            returnValue = msgBox.exec_()

        if returnValue == QMessageBox.Ok:
                
                msgBox = QMessageBox()
                msgBox.setIcon(QMessageBox.Information)
                msgBox.setText( "by by" )
                msgBox.setWindowTitle( "Пример QMessageBox" )
                msgBox.setStandardButtons(QMessageBox.Ok  )
                returnValue = msgBox.exec_()

                exit()
                



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
